### ISSUE TITLE
gzipped WARCs not indexable in OpenWayback 2.1 until unzipped

### ISSUE THREAD

**Issue by nullhandle** [ikreymer/pywb-webrecorder#11]
We used WebRecorder to record http://www.nsi.bg/census2011/pagebg2.php?p2=175&sp2=218 and the linked PDF pages one hop out but were unable to index the resulting WARCs into OpenWayback 2.1 until we unzipped them. Not sure whether this reflects an issue with WebRecorder WARC writing or OpenWayback 2.1 indexing. It's also possible that this isn't an issue in OpenWayback 2.2. Happy to provide a link to the WARC files in question, if that's helpful.

**Comment by ikreymer** [comment]
(To be clear, this is about webrecorder.io, not pywb-webrecorder, which I believe should be fine. There will soon be a issues pages for webrecorder as well)

webrecorder.io signs the WARCs so that they can be verified later, and I'm guessing that this is causing issues for openwayback, as it must not be handling gzip in a standard way. (See: [warcsigner](https://github.com/ikreymer/warcsigner))

For comparison, I  just tested these a signed WARC with `gzip -t`, [JWAT tools](https://sbforge.org/display/JWAT/Running+JWAT-Tools), and [IA CDX Writer]
(https://github.com/internetarchive/CDX-Writer), as well as the [webarchive-commons](https://github.com/iipc/webarchive-commons) indexer and the openwayback indexer.

CDX-Writer and JWAT properly parse the warc, and gzip -t reports no errors.
The openwayback indexer seems to choke on the WARC, while webarchive commons indexes the cdx, though chokes on the signature at the end.

This seems to be an openwayback indexing problem. In the meantime, I guess I can add an option to disable WARC signing...
